version: '3.1'
services:
  postgresql-container:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_PASSWORD=somepass
      - POSTGRES_USER=someuser
      - POSTGRES_DB=db-api
